# -*- coding: utf-8 -*-
"""Zomato Data Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YmHpxAeBbXhyJ53oy-MG9gzZkd4WMKf_

***Importing Libraries***
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""***1.Pandas is used for data manipulation and analysis.<br>2.Numpy is used for numerical Operations.<br>3.Matplotlib.pylot and seaborn are used for data visualization.***

***Create the dataframe***
"""

dataframe = pd.read_csv("Zomato data.csv")
print(dataframe.head())

dataframe

"""***Data Cleaning***

***Convert the datatype of column Rate to float and remove denominator***
"""

#Convert the datatype of column Rate
def handleRate(value):
  value = str(value).split("/")
  value = value[0]
  return float(value)

dataframe["rate"] = dataframe["rate"].apply(handleRate)
print(dataframe.head())

dataframe.info()

"""***Summary of the dataframe Conculsion there is no Nul value in dataframe.***

***Q1. What type of restaurant do the majority of customers order from?***
"""

#Type of Restaurant
dataframe.head()

"""***Solutions:***"""

sns.countplot(x=dataframe['listed_in(type)'], palette="viridis")
plt.xlabel("Type of Restaurant")
plt.ylabel("Count")
plt.title("Type of Restaurant Count")
plt.show()

"""***Conclusion:The majority of the restaurans fall into dining Category. Dining Restaurants are preferred by a larger number of individuals.***

***Q2.How many votes has each type of restaurant received from customers?***
"""

grouped_data = dataframe.groupby("listed_in(type)")["votes"].sum()
result = pd.DataFrame({'votes' : grouped_data})
plt.plot(result,c='green',marker='o')
plt.xlabel("Type of Restaurant")
plt.ylabel("Total Votes")
plt.title("Total Votes for Each Type of Restaurant")
plt.show()

"""***Conclusion: Dining Restaurant has Maxing Votes.***

***Q3. What are the ratings that the majority of restaurants have received?***
"""

plt.hist(dataframe["rate"],bins=5)
plt.xlabel("Ratings")
plt.ylabel("Count")
plt.title("Ratings Distribution")
plt.show()

"""***Conclusion:The majority of restaurants received ratings ranging from 3.5 to 4.The Majority of couples prefer restaurants with approximate cost of 300 rupees.***

***Q4. Zomato has observed that most couples order most of their food online.What is the averrage spending on each order?***
"""

#Average order spending by couples
couple_data = dataframe['approx_cost(for two people)']
sns.countplot(x=couple_data, palette="viridis")
plt.xlabel("Cost")
plt.ylabel("Count")
plt.title("Average order spending by Couples Cost Distribution")
plt.show()

"""***Conclusion: The majority of couples prefer resturants with an approximate cost of 300 rupees***

***Q5.Which mode (online or offline) has received the maximum rating?***
"""

plt.figure()
sns.boxplot(x=dataframe['online_order'], y=dataframe['rate'], palette="viridis")
plt.xlabel("Mode")
plt.ylabel("Rating")
plt.title("Rating Distribution by Mode")
plt.show()

"""***Conclusion: Offline orders received lower ratings in comparison to online orders, which obtained excellent ratings.***

***Q6.Which type of restaurant received more offline orders.so that Zomato can provide customer with some good offers?***
"""

pivot_table = dataframe.pivot_table(index='listed_in(type)', columns='online_order', aggfunc='size', fill_value=0)
sns.heatmap(pivot_table,annot=True,cmap="viridis", fmt='d')
plt.xlabel("Online Order")
plt.ylabel("Type of Restaurant")
plt.title("Offline Orders by Type of Restaurant")
plt.show()

"""***Conclusion:Dining restaurants primarily accept offline orders,whereas cafes primarily receive online orders.This suggests that clients prefer to place orders in person at restaurants, but prefer online ordering at cafes.***"""